name: Feature Coverage Pipeline

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Run pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          feature-monitor run-all

      - name: Publish dashboard to docs
        run: |
          mkdir -p docs/reports
          if [ -f reports/dashboard.json ]; then
            cp reports/dashboard.json docs/reports/dashboard.json
          else
            echo "reports/dashboard.json not found yet; skipping copy."
          fi

      - name: Commit data, reports, and docs
        run: |
          git config user.name "automation-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data reports docs
          git commit -m "Automated update and publish dashboard $(date +%F)" || echo "No changes"
          git push